version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 20
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
candlelight = true
everycomp = true
farmersdelight = true
spelunkery = true
simple_copper_pipes = true
doapi = true
storagedrawers = true
templates = false
brewery = true
ribbits = true
oceansdelight = true
betterend = true
enhancedcelestials = true
variantcraftingtables = true
natures_spirit = false
duckling = true
friendsandfoes = true
libraryferret = true
twigs = true
copycats = false
stonezone = true
comforts = true
justoutdoorstuffs = true
mysticsbiomes = true
diagonalwalls = false
mythicupgrades = true
sootychimneys = true
ends_delight = true
lamps = true
mcwpaths = true
nethersdelight = true
things = true
sleep_tight = true
railways = false
milk = true
amendments = true
herbalbrews = true
handcrafted = true
ftbquests = true
diagonalfences = false
heracles = true
advancednetherite = true
sophisticatedbackpacks = true
customportalapi = true
deeperdarker = true
placeables_mod_fabric = true
ironchests = true
redeco = true
cratedelight = true
supplementaries = true
suppsquared = true
chipped = true
grassoverhaul = true
clutter = true
bedspreads = true
homestead = true
beachparty = true
sawmill = true
create = false
lantern-mod = true
farm_and_charm = true
luphieclutteredmod = false
trashcans = true
biomeswevegone = true
wildernature = true
uncraftingtable76 = true
bronze = true
minecraft = true
animal_feeding_trough = true
alcocraftplus = false
lootr = true
natures_delight = false
regions_unexplored = true
mdm = true
createdeco = false
spawn = true
blahaj = true
perfectplushies = true
fetzisasiandeco = true
wetlands = true
beautify = true
wirelessredstone = true
diagonalwindows = false
umbrellas = true
villagersplus = true
questsadditions = true
vinery = true
gofish = true
toms_storage = true
meadow = true
expandeddelight = true
hearth_and_home = true
